name: 单元测试

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 设置go环境
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: 构建
      run: go build -v ./...

    - name: 测试
      run: go test -v ./...
